apps/management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('user_list', views.user_list, name='user_list'),
    path('create_voting', views.create_voting, name="create_voting"),
    path('voting_list', views.voting_list, name="voting_list"),
    path('deactivate/<int:user_id>', views.deactivate, name="deactivate"),
    path('activate/<int:user_id>', views.activate, name="activate"),
    path('voting_results/<int:voting_id>', views.voting_results, name='voting_results'),
    path('upload_padron', views.upload_padron, name='upload_padron'),
    path('download_padron', views.download_padron, name='download_padron')
]

apps/users/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import password_reset, password_reset_confirm

app_name = 'users'

urlpatterns = [
    path('new', views.create_new_emplooye, name='new'),
    path('login', views.LoginEmplooyeeView.as_view(), name='login'),
    path('logout', views.logout , name='logout'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),

    path('reset/password_reset', password_reset, {
        'template_name':'mails/reset_password/password_reset_form.html',
        'email_template_name': 'mails/reset_password/password_reset_email.html'
        }, name='password_reset'),

    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, { 
            'template_name':'mails/reset_password/password_reset_confirm.html'
            }, name='password_reset_confirm' ),    
]

apps/votings/urls.py
from django.urls import path
from . import views

app_name = 'votings'

urlpatterns = [
    path('', views.index, name='index'), 
    path('my_profile', views.my_profile, name='my_profile'), 
    path('vote/<int:voting_id>', views.vote, name='vote'),
]

votes/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.contrib.auth.views import password_reset_done, password_reset_complete
from .views import index, error_404

urlpatterns = [
    path('', index),
    path('superadmin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('votings/', include('apps.votings.urls')),
    path('management/', include('apps.management.urls')),
    path('password_reset/done', password_reset_done, {
        'template_name':'mails/reset_password/password_reset_done.html'
        }, name='password_reset_done' ),
    path('reset/password_reset_complete', password_reset_complete, {
        'template_name':'mails/reset_password/password_reset_complete.html'
        }, name='password_reset_complete'),
    re_path('[^ ]/', error_404),
]

templates/base/baseIn.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" type="image/png" href="{% static 'images/staus.ico.png' %}" />
        <title>{% block title %} {% endblock %}</title>
        {% block headss %} 
        {% endblock %}
    </head>

    <body class="fixed-nav sticky-footer bg-dark sidenav-toggled" id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <a class="navbar-brand" href="{% url 'votings:index' %}">STAUS</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Mi perfil">
                <a class="nav-link" href="{% url 'votings:my_profile' %}">
                    <i class="fa fa-fw fa-user-o"></i>
                    <span class="nav-link-text">Mi perfil</span>
                </a>
                </li>

            </ul>

            <ul class="navbar-nav sidenav-toggler">
                <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <!-- Logout  -->
                <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                    <i class="fa fa-fw fa-sign-out"></i>Cerrar Sesión</a>
                </li>
            </ul>

            </div>
        </nav>

        <div class="content-wrapper">

            {% block content %}
            {% endblock %}
            
            <!-- /.container-fluid-->
            <!-- /.content-wrapper-->
            <footer class="sticky-footer">
                <div class="container">
                    <div class="text-center">
                        <small>STAUS © 2018</small>
                    </div>
                </div>
            </footer>
            <!-- Scroll to Top Button-->
            <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
            </a>
            <!-- Logout Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">¿Estás seguro?</h5>
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">Selecciona "Cerrar Sesión" si estás seguro</div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                            <a class="btn btn-primary" href="{% url 'users:logout'%}">Cerrar Sesión</a>
                        </div>
                    </div>
                </div>
            </div>
            
            {% block bodyss %}
            {% endblock %}

        </div>
    </body>

</html>

templates/base/baseInAdmin.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" type="image/png" href="{% static 'images/staus.ico.png' %}" />
        <title>{% block title %} {% endblock %}</title>
        {% block headss %} 
        {% endblock %}
    </head>

    <body class="fixed-nav sticky-footer bg-dark sidenav-toggled" id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top sidenav-toggled" id="mainNav">
            <a class="navbar-brand" href="{% url 'management:voting_list' %}">STAUS</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
                
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Votaciones" data-original-title="Votings">
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseVotings" data-parent="#exampleAccordion" aria-expanded="false">
                        <i class="fa fa-fw fa-pencil-square"></i>
                        <span class="nav-link-text">Votaciones</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="collapseVotings" style="">
                        <li>
                            <a class="nav-link" href="{% url 'management:create_voting' %}">
                                <i class="fa fa-fw fa-plus-circle"></i>
                                <span class="nav-link-text">Crear votacion</span>
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'management:voting_list' %}">
                                <i class="fa fa-fw fa-list-alt"></i>
                                <span class="nav-link-text">Lista de votaciones</span>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Usuarios">
                    <a class="nav-link" href="{% url 'management:user_list' %}">
                        <i class="fa fa-fw fa-list-alt"></i>
                        <span class="nav-link-text">Usuarios</span>
                    </a>
                </li>
            </ul>

            <ul class="navbar-nav sidenav-toggler">
                <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <!-- Logout  -->
                <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                    <i class="fa fa-fw fa-sign-out"></i>Cerrar Sesión</a>
                </li>
            </ul>

            </div>
        </nav>

        <div class="content-wrapper">

            {% block content %}
            {% endblock %}
            
            <!-- /.container-fluid-->
            <!-- /.content-wrapper-->
            <footer class="sticky-footer">
                <div class="container">
                    <div class="text-center">
                        <small>STAUS © 2018</small>
                    </div>
                </div>
            </footer>
            <!-- Scroll to Top Button-->
            <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
            </a>
            <!-- Logout Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">¿Estás seguro?</h5>
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">Selecciona "Cerrar Sesión" si estás seguro</div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                            <a class="btn btn-primary" href="{% url 'users:logout'%}">Cerrar Sesión</a>
                        </div>
                    </div>
                </div>
            </div>
            
            {% block bodyss %}
            {% endblock %}

        </div>
    </body>

</html>

templates/base/baseOut.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" type="image/png" href="{% static 'images/staus.ico.png' %}" />
        <title>{% block title %} {% endblock %}</title>
        {% block headss %} 
        {% endblock %}
    </head>
    <body class="bg-dark">
        <div class="container">
            {% block content %}
    
            {% endblock %}
    
            {% block bodyss %}
            {% endblock %}
        </div>
    </body>
</html>