apps/management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('user_list', views.user_list, name='user_list'),
    path('create_voting', views.create_voting, name="create_voting"),
    path('voting_list', views.voting_list, name="voting_list"),
    path('deactivate/<int:user_id>', views.deactivate, name="deactivate"),
    path('activate/<int:user_id>', views.activate, name="activate"),
    path('voting_results/<int:voting_id>', views.voting_results, name='voting_results'),
    path('upload_padron', views.upload_padron, name='upload_padron'),
    path('download_padron', views.download_padron, name='download_padron')
]

votes/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.contrib.auth.views import password_reset_done, password_reset_complete
from .views import index, error_404

urlpatterns = [
    path('', index),
    path('superadmin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('votings/', include('apps.votings.urls')),
    path('management/', include('apps.management.urls')),
    path('password_reset/done', password_reset_done, {
        'template_name':'mails/reset_password/password_reset_done.html'
        }, name='password_reset_done' ),
    path('reset/password_reset_complete', password_reset_complete, {
        'template_name':'mails/reset_password/password_reset_complete.html'
        }, name='password_reset_complete'),
    re_path('[^ ]/', error_404),
]

apps/management/models.py
from django.db import models
from apps.users.models import Delegacion

# Create your models here.
class Voting(models.Model):
    delegacion = models.ForeignKey(Delegacion, on_delete=models.PROTECT, null=True)
    tema = models.TextField(blank=False, null=False)
    pregunta = models.TextField(blank=False, null=False)
    fecha_de_inicio = models.DateTimeField(auto_now=False)
    fecha_de_cierre = models.DateTimeField(auto_now=False)

    def __str__(self):
        return '{}: {}'.format(self.tema, self.pregunta)

class Answer(models.Model):
    votacion = models.ForeignKey(Voting, on_delete=models.PROTECT)
    respuesta = models.TextField(blank=False, null=False)

    def __str__(self):
        return '{}: {}'.format(self.votacion, self.respuesta)
        

apps/management/forms.py
from django import forms

apps/management/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Voting, Answer
from apps.users.models import Padron, Delegacion
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.http import JsonResponse
from datetime import datetime, timedelta
import pytz
# csv
import csv
from django.http import HttpResponse, StreamingHttpResponse

def get_users():
    return list(User.objects.raw("""
        SELECT 1 id, au.id as user_id, ud.nombre as delegacion, up.numero_de_empleado, up.nombre_completo, au.is_active
        FROM users_padron up 
        JOIN users_delegacion ud ON ud.id = up.delegacion_id
        JOIN auth_user au
        WHERE au.username = up.numero_de_empleado"""))
    
@login_required(login_url='users:login')
def user_list(request):
    
    if request.user.is_staff == True:
        return render(request, 'management/user_list.html', {'users':get_users()})
    else:
        return redirect('votings:index')

def get_delegacion_names():
    delegaciones = list(Delegacion.objects.all().values())
    delegaciones_names = []
    
    for d in delegaciones:
        if d['nombre'] != "TODAS":
            delegaciones_names.append( d['nombre'] )

    delegaciones_names.sort()
    # para ponerla al inicio
    delegaciones_names.insert(0, "TODAS")

    return delegaciones_names

def get_date(fecha):
    date = fecha[0].split("-") # 2017-03-07 13:00, 2018-03-07 14:00 
    hour_and_minute = fecha[1].split(":")
    return datetime(year=int(date[0]), month=int(date[1]), day=int(date[2]), 
        hour=int(hour_and_minute[0]), minute=int(hour_and_minute[1]))

def get_dates(fecha_de_inicio, fecha_de_cierre):
    return get_date(fecha_de_inicio), get_date(fecha_de_cierre)

def save_voting(post):
    tema, pregunta = post['tema'], post['pregunta']
    fecha_de_inicio, fecha_de_cierre = get_dates([post['fecha_de_inicio'], post['hora_de_inicio']], 
        [ post['fecha_de_cierre'], post['hora_de_cierre']])

    if fecha_de_inicio < datetime.now():
        return {'tipo': 0, 'd_names':get_delegacion_names()}
    elif fecha_de_cierre < fecha_de_inicio:
        return {'tipo': 1, 'd_names':get_delegacion_names()}
    # creo el votacion
    voting = Voting()
    voting.tema = tema
    voting.pregunta = pregunta
    voting.delegacion = Delegacion.objects.get(nombre=post['delegacion'])
    voting.fecha_de_inicio = fecha_de_inicio
    voting.fecha_de_cierre = fecha_de_cierre
    voting.save()
    # creo las respuestas y las guardo
    # len(post)-8 = numero de respuestas
    for i in range(len(post)-8): 
        answer = Answer()
        answer.respuesta = post['op{}'.format(i+1)]
        answer.votacion = voting
        answer.save()
    return None

@login_required(login_url='users:login')
def create_voting(request):
    
    if request.method == 'GET':
        
        if request.user.is_staff == True:
            return render(request, 'management/create_voting.html', {'d_names':get_delegacion_names()})
        else:
            return redirect('votings:index')

    else:
        error = save_voting(request.POST)
        if error is None:
            return redirect('management:voting_list')
        else:
            print(error)
            return render(request, 'management/create_voting.html', error)

def send_email(request, template, subject, user, case=0):
    # get dominio
    current_site = get_current_site(request)
    context = ({'user':user, 'razon': request.POST['razon']} if case == 0 else {'user':user})
    message = render_to_string(template, context)
    # crea y envia el mensaje
    email = EmailMessage(
        subject, message, to=[user.email]
    )
    email.send()

@login_required(login_url='users:login')
def deactivate(request, user_id):
    if request.method == 'POST':
        try:
            user_desactivate = User.objects.get(id=user_id)
            user_desactivate.is_active = False
            user_desactivate.save()
            send_email(request, 'mails/desactivar_usuario.html', 
                'Su cuenta a sido desactivada', user_desactivate)
            print("se cambio")
            return redirect('management:user_list')
        except User.DoesNotExist:
            print("no existe")
            return redirect('management:user_list') 
    else:
        
        if request.user.is_staff == True:
            return redirect('management:user_list')
        else:
            return redirect('votings:index')

@login_required(login_url='users:login')
def activate(request, user_id):
    if request.method == 'POST':
        try:
            user_activate = User.objects.get(id=user_id)
            user_activate.is_active = True
            user_activate.save()
            send_email(request, 'mails/activar_usuario.html', 
                'Su cuenta a sido activada', user_activate, case=1)
            return redirect('management:user_list')
        except User.DoesNotExist:
            return redirect('management:user_list') 
    else:
        
        if request.user.is_staff == True:
            return redirect('management:user_list')
        else:
            return redirect('votings:index')

def get_date_str(date):
    seven_hours = timedelta(hours=7)
    fecha = date - seven_hours
    return fecha.strftime("20%y/%m/%d %H:%M")

def get_today():
    #saca la zona horaria de hermosillo
    timezone = pytz.timezone("America/Hermosillo")
    #le pone la zona horaria y la trnaforma para poder comparar
    return timezone.localize(datetime.now())

def get_votings():
    voting_list = list(Voting.objects.all().values())
    votings = []
    # los paso a string, para convertir la fecha
    for v in voting_list:
        voting = {
            'id': v['id'],
            'tema': v['tema'],
            'fecha_de_inicio_str': get_date_str(v['fecha_de_inicio']),
            'fecha_de_cierre_str': get_date_str(v['fecha_de_cierre']),
            'fecha_de_inicio': v['fecha_de_inicio'],
            'fecha_de_cierre': v['fecha_de_cierre'],
        }
        votings.append(voting)

    return votings

@login_required(login_url='users:login')
def voting_list(request):
    
    if request.user.is_staff == True:
        context = {
            'votings': get_votings(),
            'fecha': get_today()
        }
        return render(request, 'management/voting_list.html', context)
    else:
        return redirect('votings:index')

def get_users_who_voted(voting_id):
    users_who_voted = list(Delegacion.objects.raw("""
        SELECT 1 id, d.nombre delegacion, p.numero_de_empleado, p.nombre_completo
        FROM votings_ivoted iv
        JOIN auth_user u ON u.id = iv.usuario_id
        JOIN users_padron p ON p.numero_de_empleado = u.username
        JOIN users_delegacion d ON p.delegacion_id = d.id
        WHERE iv.votacion_id = %s
        ORDER BY delegacion ASC""", [voting_id] ))

    users_who_voted_list = []
    # obtengo las personas que votaron
    for user_who_voted in users_who_voted:
        user_v = {
            'delegacion': user_who_voted.delegacion,
            'numero_de_empleado': user_who_voted.numero_de_empleado,
            'nombre_completo': user_who_voted.nombre_completo,
        }
        users_who_voted_list.append(user_v)

    return users_who_voted_list

def get_voting_results(voting_id):
    
    try:
        voting_results =  list(Voting.objects.raw("""
        SELECT 1 id, vg.tema, vg.pregunta, a.respuesta, COUNT(*) votos
        FROM votings_vote v
        JOIN management_voting vg ON vg.id = v.votacion_id
        JOIN management_answer a ON a.id = v.respuesta_id
        WHERE v.votacion_id = %s
        GROUP BY a.respuesta ORDER BY votos DESC""", [voting_id]))

        # obtengo los datos de la votacion
        votacion = {
            'tema': voting_results[0].tema,
            'pregunta': voting_results[0].pregunta
        }
    except:
        # si no hay votaciones, se obtiene la votacion
        voting = Voting.objects.get(id=voting_id)
        votacion = {
            'tema': voting.tema,
            'pregunta': voting.pregunta
        }
        voting_results = []


    voting_results_list = []
    # obtengo las respuestas con sus votos
    for voting_result in voting_results:
        voting = {
            'respuesta': voting_result.respuesta,
            'votos': voting_result.votos
        }
        voting_results_list.append(voting)

    # agrego alguna respuesta si es que falto
    answers_of_voting = list(Answer.objects.filter(votacion_id=voting_id).values())
    answers_of_voting = [ v['respuesta'] for v in answers_of_voting ]

    for answer_of_voting in answers_of_voting:
        if answer_of_voting not in ( voting['respuesta'] for voting in voting_results_list):
            voting_results_list.append({
                'respuesta': answer_of_voting,
                'votos': 0
            })

    return votacion, voting_results_list

@login_required(login_url='users:login')
def voting_results(request, voting_id):
    
    if request.method == 'POST':
        #saca la zona horaria de hermosillo
        timezone = pytz.timezone("America/Hermosillo")
        #le pone la zona horaria y la trnaforma para poder comparar
        fecha = timezone.localize(datetime.now())
        users_who_voted = get_users_who_voted(voting_id) 
        votacion, voting_results = get_voting_results(voting_id)
        return JsonResponse({ 
            'votacion': votacion,
            'users': users_who_voted, 
            'results': voting_results,
            'fecha' : fecha 
        })
    else:
        return redirect('management:voting_list')

def clean_padron(dirty_padron):
    padron_clean = []
    padron_space = dirty_padron.split(",")
    for p in padron_space:
        padron_clean.append(p)
    return padron_clean

templates/management/create_voting.html
{% extends "base/baseInAdmin.html" %}

{% block title %}Crear votacion{% endblock %}

{% block headss %} 
    {% load staticfiles %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">

{% endblock %}

{% block content %}

    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Votación</li>
            <li class="breadcrumb-item active">Crear</li>
        </ol>
        
        <!-- Breadcrumbs-->
        <div class="card card-register mx-auto mt-5">
            <div class="card-header" align="center">
                <img src="{% static 'images/logoNombre.png' %}" width="247" height="91" alt="STAUS" alin>
            </div>
            <div class="card-header" align="center">
                Crear votación
            </div>
            <div class="card-body">
                <form method="post">{% csrf_token %}
                    
                    {% if tipo == 0 %}    
                        <div class="alert alert-danger" role="alert">
                            La fecha de inicio no puede ser antes que la fecha actual.
                        </div>
                    {% elif tipo == 1 %}
                        <div class="alert alert-danger" role="alert">
                            La fecha de cierre no puede ser antes que la fecha de inicio.
                        </div>
                    {% endif %}

                    <div class="card mb-3">
                        <div class="card-body">
                            Nota: Si la votación sera para todas las delegaciones, 
                            seleccionar la opción "TODAS".
                        </div>
                      </div>

                    <div class="form-group">
                        <label for="delegacion">Delegación</label>
                        <select class="form-control" name="delegacion" id="station">
                            {% for d in d_names %}
                                {% if d == user.delegacion %}
                                    <option selected>{{ d }}</option>
                                {% else %}
                                    <option>{{ d }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="tema">Tema</label>
                        <input class="form-control" type="text" name="tema" placeholder="El tema es..." required>
                    </div>

                    <div class="form-group">
                        <label for="pregunta">Pregunta</label>
                        <input class="form-control" type="text" name="pregunta" placeholder="¿La pregunta es?" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="delegacion">Número de opciones</label>
                            <select id="num_op" class="form-control">
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                    </div>

                    <div id="respuestas">
                        <div class="form-group">
                            <label for="respuesta1">Opcion 1</label>
                            <!-- <input class="form-control" type="text" name="op1" required> -->
                            <textarea class="form-control" rows="3" name="op1" required></textarea>
                        </div>

                        <div class="form-group">
                            <label for="respuesta2">Opcion 2</label>
                            <!-- <input class="form-control" type="text" name="op2" required> -->
                            <textarea class="form-control" rows="3" name="op2" required></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="fecha_de_inicio">Fecha de inicio</label>
                                <input id="date1" class="form-control" type="date" name="fecha_de_inicio" required>
                            </div>
                            <div class="col-md-6">
                                <label for="hora_de_inicio">Hora de inicio</label>
                                <input class="form-control" type="time" name="hora_de_inicio" value="13:00" required>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="fecha_de_cierre">Fecha de cierre</label>
                                <input id="date2" class="form-control" type="date" name="fecha_de_cierre" required>
                            </div>
                            <div class="col-md-6">
                                <label for="hora_de_cierre">Hora de cierre</label>
                                <input class="form-control" type="time" name="hora_de_cierre" value="14:00" required>
                            </div>
                        </div>
                    </div>

                    <input type="submit" class="btn button-caution btn-block" value="Crear">
                </form>
            </div>
        </div>
        
    </div>

{% endblock %}

{% block bodyss %}
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.j' %}s"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script src="{% static 'js/fechas/date_start.js' %}"></script>
    <script src="{% static 'js/respuestas/cambiar_respuestas.js' %}"></script>
{% endblock %}

templates/management/user_list.html
{% extends "base/baseInAdmin.html" %}

{% block title %}Lista de usuarios{% endblock %}

{% block headss %} 
    {% load staticfiles %}
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Lista de usuarios</li>
            <li class="breadcrumb-item active">Lista</li>
        </ol>
        <div class="card mb-3">
            <div class="card-header">
            <i class="fa fa-fw fa-table"></i>Lista de usuarios</div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Delegación</th>
                                <th>Número de empleado</th>
                                <th>Nombre</th>
                                <th>Acción</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                                {% if user.is_active == True %}
                                    <tr>
                                        <td>{{user.delegacion}}</td>
                                        <td>{{user.numero_de_empleado}}</td>
                                        <td>{{user.nombre_completo}}</td>
                                        <td>
                                            <a href="#" data-toggle="modal" data-target="#desactivateModal{{user.user_id}}" class="btn btn-danger">Desactivar</a>
                                        </td>
                                    </tr>
                                    <div id="desactivateModal{{user.user_id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" class="modal fade">
                                        <div role="document" class="modal-dialog">
                                            <div class="modal-content">
                                                <form method="post" action="{% url 'management:deactivate' user.user_id %}">{% csrf_token %}
                                                    <div class="modal-header">
                                                        <h5 id="exampleModalLabel" class="modal-title">Desactivar usuario</h5>
                                                        <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                        <p>Nota: Debe escribir las razones por las cual el usuario no puede votar en linea.</p>
                                                        <label for="correccion" class="col-form-label">Razones:</label>
                                                        <textarea name="razon" rows="4" class="form-control" required></textarea>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-primary">Aceptar</button>
                                                        <button data-dismiss='modal' class="btn btn-secondary">Cancelar</button>
                                                    </div>  
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                {% else %}
                                    <tr>
                                        <td>{{user.delegacion}}</td>
                                        <td>{{user.numero_de_empleado}}</td>
                                        <td>{{user.nombre_completo}}</td>
                                        <td>
                                            <a href="#" data-toggle="modal" data-target="#activateModal{{user.user_id}}" class="btn btn-danger">Activar</a>
                                        </td>
                                    </tr>
                                    <div id="activateModal{{user.user_id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" class="modal fade">
                                        <div role="document" class="modal-dialog">
                                            <div class="modal-content">
                                                <form method="post" action="{% url 'management:activate' user.user_id %}">{% csrf_token %}
                                                    
                                                    <div class="modal-header">
                                                        <h5 id="exampleModalLabel" class="modal-title">Activar usuario</h5>
                                                        <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                        <p>¿Esta seguro que quiere activar al usuario?</p>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-primary">Aceptar</button>
                                                        <button data-dismiss='modal' class="btn btn-secondary">Cancelar</button>
                                                    </div>  
                                                </form> 
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

{% block bodyss %}
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.j' %}s"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static 'js/sb-admin-datatables.min.js' %}"></script>
    <script>
        $('#dataTable').DataTable({
            responsive: true,
            "order": [[ 0, "asc" ]]
        });
    </script>
{% endblock %}

templates/management/voting_list.html
{% extends "base/baseInAdmin.html" %}

{% block title %}Lista de votaciones{% endblock %}

{% block headss %} 
    {% load staticfiles %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">

{% endblock %}

{% block content %}

    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Lista de votaciones</li>
            <li class="breadcrumb-item active">Lista</li>
        </ol>
        <div class="card mb-3">
            <div class="card-header">
            <i class="fa fa-fw fa-table"></i>Lista de votaciones</div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Tema</th>
                                <th>Fecha de inicio</th>
                                <th>Fecha de cierre</th>
                                <th>Acción</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for voting in votings %}
                                <tr>
                                    <td>{{voting.tema}}</td>
                                    <td>{{voting.fecha_de_inicio_str}}</td>
                                    <td>{{voting.fecha_de_cierre_str}}</td>
                                    {% if fecha > voting.fecha_de_cierre %}
                                        <td>
                                            <form id="form{{voting.id}}" action="{% url 'management:voting_results' voting.id %}" method="POST">{% csrf_token %}
                                                <button type="button" class="btn btn-success pdf {{voting.id}}">Resultado</button>
                                            </form>
                                        </td>
                                    {% else %}
                                        <td>
                                            <button type="button" class="btn btn-success" title="La votación aun no se ha cerrado" disabled>Resultado</button>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

{% block bodyss %}
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.j' %}s"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static 'js/sb-admin-datatables.min.js' %}"></script>
    <script>
        $('#dataTable').DataTable({
            responsive: true,
            "order": [[ 1, "desc" ]]
        });
    </script>
    <script src="{% static 'js/pdf/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/pdf/vfs_fonts.js' %}"></script>
    <script src="{% static 'js/pdf/results.js' %}"></script>
{% endblock %}