apps/votings/urls.py
from django.urls import path
from . import views

app_name = 'votings'

urlpatterns = [
    path('', views.index, name='index'), 
    path('my_profile', views.my_profile, name='my_profile'), 
    path('vote/<int:voting_id>', views.vote, name='vote'),
]

votes/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.contrib.auth.views import password_reset_done, password_reset_complete
from .views import index, error_404

urlpatterns = [
    path('', index),
    path('superadmin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('votings/', include('apps.votings.urls')),
    path('management/', include('apps.management.urls')),
    path('password_reset/done', password_reset_done, {
        'template_name':'mails/reset_password/password_reset_done.html'
        }, name='password_reset_done' ),
    path('reset/password_reset_complete', password_reset_complete, {
        'template_name':'mails/reset_password/password_reset_complete.html'
        }, name='password_reset_complete'),
    re_path('[^ ]/', error_404),
]

apps/votings/models.py
from django.db import models
from apps.management.models import Voting, Answer
from django.contrib.auth.models import User
# Create your models here.
class Vote(models.Model):
    votacion = models.ForeignKey(Voting, on_delete=models.PROTECT)
    respuesta = models.ForeignKey(Answer, on_delete=models.PROTECT)
    
    def __str__(self):
        return '{}'.format(self.respuesta)

class IVoted(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    votacion = models.ForeignKey(Voting, on_delete=models.PROTECT)
    fecha = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}: {}: {}'.format(self.votacion, self.usuario, self.fecha)

apps/votings/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, update_session_auth_hash
from django.contrib import messages
from apps.management.models import Voting, Answer
from apps.users.models import Delegacion
from .models import Vote, IVoted
import datetime
import pytz

# Create your views here.
def get_encuestas(usuario):
    #return list(Voting.objects.all().order_by('-fecha_de_inicio'))
    delegacion_usuario = Delegacion.objects.get(nombre=usuario.delegacion)
    delegacion_all = Delegacion.objects.get(nombre="TODAS")
    delegaciones = [delegacion_usuario.id, delegacion_all.id]

    return list(Voting.objects.raw("""
        SELECT 1 idd, mv.id, mv.tema, mv.pregunta, mv.fecha_de_inicio, mv.fecha_de_cierre
        FROM management_voting mv
        WHERE mv.delegacion_id IN %s 
        ORDER BY mv.fecha_de_inicio DESC""", [delegaciones]))

def get_respuestas(encuestas):
    #return list(Answer.objects.all())

    encuestas_ids = [ e.id for e in encuestas ]

    return list(Answer.objects.raw("""
        SELECT 1 idd, ma.id, ma.votacion_id, ma.respuesta
        FROM management_answer ma
        WHERE ma.votacion_id IN %s """, [encuestas_ids]))

def get_resultados(encuestas):
    voting_ids = [ e.id for e in encuestas ]

    voting_results = list(Voting.objects.raw("""
        SELECT 1 id, v.votacion_id, a.respuesta, COUNT(*) votos
        FROM votings_vote v
        JOIN management_voting vg ON vg.id = v.votacion_id
        JOIN management_answer a ON a.id = v.respuesta_id
        WHERE v.votacion_id IN %s
        GROUP BY a.respuesta, v.votacion_id ORDER BY votos DESC""", [voting_ids]))

    answers_with_zero_votes = []
    for v_id in voting_ids:
        # agrego alguna respuesta si es que falto
        answers_of_voting = list(Answer.objects.filter(votacion_id=v_id).values())
        # se agregan las respuestas de la votacion con votos
        voting_result = []
        for v in voting_results:
            if v.votacion_id == v_id:
                voting_result.append(v.respuesta)
    
        # se agregan las respuestas con cero votos
        for answer_of_voting in answers_of_voting:
            if answer_of_voting['respuesta'] not in voting_result:
                answers_with_zero_votes.append({
                    'id':1,
                    'votacion_id': v_id,
                    'respuesta': answer_of_voting['respuesta'],
                    'votos': 0
                })    

    return voting_results + answers_with_zero_votes

def get_iVoted(request):
    return list(IVoted.objects.filter(usuario=request.user))   

def get_iVotedPregunta(request):
    return list(IVoted.objects.all())   

def get_user(request):
    return list(User.objects.raw("""
        SELECT 1 id, d.nombre delegacion, p.numero_de_empleado, p.nombre_completo, u.email
        FROM auth_user u
        JOIN users_padron p ON p.numero_de_empleado = u.username
        JOIN users_delegacion d ON p.delegacion_id = d.id
        WHERE u.username = %s""", [request.user.username]))[0]

@login_required(login_url='users:login')
def index(request):
    
    if request.method == 'GET':
        
        if request.user.is_staff == False:
            usuario = get_user(request)
            encuestas = get_encuestas(usuario)
            respuestas = get_respuestas(encuestas)
            resultados = []
            ivoted = get_iVoted(request)
            #nomas tomar los id's
            votos = [i.votacion.id for i in ivoted]
            #saca la zona horaria de hermosillo
            timezone = pytz.timezone("America/Hermosillo")
            #le pone la zona horaria y la trnaforma para poder comparar
            ahora = timezone.localize(datetime.datetime.now())
            #nomas agarrar el de la fecha d einicio mayor"
            encuesta = []

            if len(encuestas) > 1:
                encuesta.append(encuestas[0])
                encuesta.append(encuestas[1])
                resultados = get_resultados(encuesta)
            elif len(encuestas) == 1:
                encuesta.append(encuestas[0])
                resultados = get_resultados(encuesta)

            if 'show2' not in request.session:
                request.session['show2'] = False
                return render(request, 'votings/index.html', {
                    'encuestas': encuesta,
                    'respuestas': respuestas,
                    'resultados': resultados,
                    'votos': votos,
                    'fecha':ahora,
                    'show2':True
                })
            else:
                return render(request, 'votings/index.html', {
                    'encuestas': encuesta,
                    'respuestas': respuestas,
                    'resultados': resultados,
                    'votos': votos,
                    'fecha':ahora,
                    'show2':False
                })

        else:
            return redirect('management:user_list')

@login_required(login_url='users:login')
def vote(request, voting_id):
    
    if request.method == 'POST':
        #para checar si no ha pasado la fecha y est fuera de tiempo
        votacion = Voting.objects.get(id=voting_id)
        #saca la zona horaria de hermosillo
        timezone = pytz.timezone("America/Hermosillo")
        #le pone la zona horaria y la trnaforma para poder comparar
        ahora = timezone.localize(datetime.datetime.now())
        #calcula si esta fuera de tiempo
        fueraDeTiempo=votacion.fecha_de_cierre<ahora
        #hace una consulta y si encuentra que el usuario respondio esa pregunta lo guarda en yaVoto y si no sta vacia la variable
        yaVoto=list(IVoted.objects.filter(usuario=request.user,votacion_id=voting_id))
        #si no ha votado guarda y no ha pasado la fecha de cierre el voto
        if (not yaVoto) and (not fueraDeTiempo) and ('choice' in request.POST): 
            # ivoted_p = IVoted(usuario_id=request.user.id, votacion_id=votacion_id)
            # obtengo la votacion y la respuesta
            try:
                votacion = Voting.objects.get(id=voting_id)
                respuesta = Answer.objects.get(id=request.POST['choice'])
                #crea y guardo el voto
                vote = Vote()
                vote.votacion = votacion
                vote.respuesta = respuesta
                vote.save()
                # creo y guardo que el usuario a votado en esa votacion
                ivoted = IVoted()
                ivoted.usuario = request.user
                ivoted.votacion = votacion
                ivoted.save()
            except:
                print("Error votacion o respuesta null")
        #si ya voto le recrimina por trampa    
        else: 
            print("Ya habia votado o es fuera de tiempo")

    if request.user.is_staff == False:
        return redirect('votings:index')
    else:
        return redirect('management:user_list')

@login_required(login_url='users:login')
def my_profile(request):
    
    if request.method == 'GET':
        
        if request.user.is_staff == False:
            return render(request, 'votings/my_profile.html', {'user':get_user(request)})
        else:
            return redirect('management:user_list')

    else:
        # cambio el password
        password_old = request.POST['password_old'] if 'password_old' in request.POST else 'noexiste123'
        password_new1 = request.POST['password_new1'] if 'password_new1' in request.POST else 'noexiste123'
        password_new2 = request.POST['password_new2'] if 'password_new2' in request.POST else 'noexiste124'

        if password_new1 == password_new2:

            if authenticate(username=request.user.username, password=password_old):
                request.user.set_password(password_new1)
                request.user.save()                
                update_session_auth_hash(request, request.user)
                messages.success(request, 'Contraseña actualizada')
            else:
                messages.error(request, 'La contraseña actual no coincide') 

        else:
            messages.error(request, 'Las contraseñas no coinciden') 

        return render(request, 'votings/my_profile.html', {'user':get_user(request)})

templates/votings/index.html
{% extends "base/baseIn.html" %}

{% block title %}Votaciones{% endblock %}

{% block headss %} 
    {% load staticfiles %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Inicio</li>
            <li class="breadcrumb-item active">Votaciones disponibles</li>
        </ol>
        <div class="row">
            {% if encuestas %}
            <!--Si hay encuestas disponibles--> 
            <div class="col-12">
                <div class="row">
                    {% for encuesta in encuestas %}
                    <div class="col-md-8 offset-md-2">
                    <!-- <div class="col-md-6"> -->    
                        <div class="card mb-3">    
                            <div class="card-header">
                                <i class="fa fa-pencil-square"></i> {{ encuesta.tema }}</div>
                                <div class="card-body">
                                    {% if encuesta.fecha_de_inicio > fecha %}
                                    <!-- si aun no inicia la votacion -->
                                        <div class="form-group">
                                            <label>{{ encuesta.pregunta }}</label>
                                            <br><br>
                                            <center>
                                                <div class="mr-5">La votación aún no inicia.</div>
                                            </center>
                                            <hr>
                                            <div class="mr-5">Fecha de inicio: {{ encuesta.fecha_de_inicio }}</div>
                                        </div>
                                    {% elif encuesta.fecha_de_cierre > fecha %}
                                    <!-- en proceso de votación -->
                                        {% if votos %}
                                        <!--Aqui es si el usuario ha votado en alguna encuesta--> 
                                            {% if encuesta.id in votos %}
                                                <!--si ya voto en la encuesta-->
                                                <div class="form-group">
                                                    <label>{{ encuesta.pregunta }}</label>
                                                    <br><br>
                                                    <center>
                                                        <!-- <div class="mr-5">Ya participó en esta votación</div> -->
                                                        <div class="mr-5">Gracias por participar, su voto ha sido registrado</div>
                                                    </center>
                                                    <hr>
                                                    <div class="mr-5">Fecha de cierre: {{ encuesta.fecha_de_cierre }}</div>
                                                </div>
                                            {% else %}
                                                <!--si no ha votado en la encuesta-->
                                                <form action="{% url 'votings:vote' encuesta.id %}" method="post">{% csrf_token %}
                                                    <div class="form-group">
                                                        <label>{{ encuesta.pregunta }}</label>
                                                        <br><br>
                                                        {% for respuesta in respuestas %}
                                                            {% if encuesta.id == respuesta.votacion_id %}
                                                            <div class="radio">
                                                                <label>
                                                                    <input type="radio" name="choice" id="choice{{respuesta.id}}" value="{{respuesta.id}}"> {{ respuesta.respuesta }}
                                                                </label>
                                                            </div>
                                                            {% endif %}
                                                        {% endfor %}
                                                        <center>
                                                            <input type="submit" class="btn button-caution" value="Votar" ali>
                                                        </center>
                                                        <hr>
                                                        <div class="mr-5">Fecha de inicio: {{ encuesta.fecha_de_inicio }}</div>
                                                        <hr>
                                                        <div class="mr-5">Fecha de cierre: {{ encuesta.fecha_de_cierre }}</div>
                                                    </div>
                                                </form>
                                            {% endif %}
                                        {% else %}  
                                            <!--Aqui es si no hay ninguna votacion del usuario-->    
                                            <form action="{% url 'votings:vote' encuesta.id %}" method="post">{% csrf_token %}
                                                <div class="form-group">
                                                    <label>{{ encuesta.pregunta }}</label>
                                                    <br><br>
                                                    {% for respuesta in respuestas %}
                                                        {% if encuesta.id == respuesta.votacion_id %}
                                                        <div class="radio">
                                                            <label>
                                                                <input type="radio" name="choice" id="choice{{respuesta.id}}" value="{{respuesta.id}}"> {{ respuesta.respuesta }}
                                                            </label>
                                                        </div>
                                                        {% endif %}
                                                    {% endfor %}
                                                    <center>
                                                        <input type="submit" class="btn button-caution" value="Votar" ali>
                                                    </center>
                                                    <hr>
                                                    <div class="mr-5">Fecha de inicio: {{ encuesta.fecha_de_inicio }}</div>
                                                    <hr>
                                                    <div class="mr-5">Fecha de cierre: {{ encuesta.fecha_de_cierre }}</div>
                                                </div>
                                            </form>
                                        {% endif %}   
                                    {% else %}
                                    <!-- si ya paso la votacion -->
                                    <div class="form-group">
                                        <label>{{ encuesta.pregunta }}</label>
                                        <br><br>
                                        <center>
                                            <div class="mr-5">La votación ha concluido.</div>
                                        </center>
                                        <hr>
                                        <div class="col-12">
                                            <div class="row">
                                                <div class="col-md-8 offset-md-2">
                                                    <center>
                                                        <div class="mr-5">Resultados de la votación en línea (prueba piloto)</div>
                                                    </center>
                                                    <br>
                                                    <table class="table table-bordered table-striped">
                                                        <thead>
                                                        <tr class="text-center">
                                                            <th>Opción</th>
                                                            <th>Votos</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for resultado in resultados %}
                                                                {% if resultado.votacion_id == encuesta.id %}
                                                                    <tr>
                                                                        <td>{{ resultado.respuesta }}</th>
                                                                        <td class="text-center">{{ resultado.votos }}</td>
                                                                    </tr>
                                                                {% endif %}
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>    
                                        <hr>
                                        <div class="mr-5">La votación terminó el {{ encuesta.fecha_de_cierre }}</div>
                                    </div>
                                    {% endif %}
                                </div>
                            <div class="card-footer small text-muted"></div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
                <!--
                {% if show2 == True %}
                    <div id="voteModal" tabindex="-1" role="dialog" class="modal">
                        <div role="document" class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title">Aviso</h5>
                            <button type="button" data-dismiss="modal" aria-label="Close" class="close"></button><span aria-hidden="true">×</span>
                            </div>
                            <div class="modal-body">
                            <p>Bienvenidos a la consulta "Plebiscito STAUS sobre la problemática del ISSSTESON".
                                Este tipo de consulta (Vía electrónica) está en periodo de prueba, por lo tanto, no será considerada para este proceso.</p>
                            </div>
                            <div class="modal-footer">
                                <button data-dismiss='modal' class="btn btn-primary">Aceptar</button>
                            </div>
                        </div>
                        </div>
                    </div>
                {% endif %}
                -->
            {% else %}
            <!--Si no hay encuestas--> 
                <div id="voteModal" tabindex="-1" role="dialog" class="modal">
                    <div role="document" class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title">Aviso</h5>
                        <button type="button" data-dismiss="modal" aria-label="Close" class="close"></button><span aria-hidden="true">×</span>
                        </div>
                        <div class="modal-body">
                        <p>No hay votaciones</p>
                        </div>
                        <div class="modal-footer">
                            <button data-dismiss='modal' class="btn btn-primary">Aceptar</button>
                        </div>
                    </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block bodyss %}
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.j' %}s"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script src="{% static 'js/buttons.js' %}"></script>
    <!--
    <script language="javascript" type="text/javascript">
        $(document).ready(function(){
            $('#voteModal').modal('show')
        });
    </script>
    -->
{% endblock %}

templates/votings/my_profile.html
{% extends "base/baseIn.html" %}

{% block title %}Mi perfil{% endblock %}

{% block headss %} 
    {% load staticfiles %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">{{ user.nombre_completo }}</li>
            <li class="breadcrumb-item active">Mi perfil</li>
        </ol>
        <!-- Example DataTables Card-->
        <div class="card card-register mx-auto mt-5">
            <div class="card-header">Mi perfil</div>
            <div class="card-body">
                <form method="post">{% csrf_token %}
                    {% if messages %}
                        {% for message in messages  %}
                            {% if message.tags == 'error' %} 
                                <div class="alert alert-danger" role="alert">
                                    {{message}}
                                </div>
                            {% elif message.tags == 'success' %}
                                <div class="alert alert-success" role="alert">
                                        {{message}}
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" value="{{ user.nombre_completo }}" class="form-control" disabled="disabled"/>
                    </div>
                    <div class="form-group">
                        <label for="correo">Correo Electrónico</label>
                        <input type="email" value="{{ user.email }}" class="form-control" disabled="disabled"/>
                    </div>
                    <div class="form-group">
                        <label for="correo">Delegación</label>
                        <input type="text" value="{{ user.delegacion }}" class="form-control" disabled="disabled"/>
                    </div>
                    <div class="form-group">
                        <label for="correo">Número de empleado</label>
                        <input type="text" value="{{ user.numero_de_empleado }}" class="form-control" disabled="disabled"/>
                    </div>
                    <div class="form-group">
                        <label for="password_old">Contraseña actual</label>
                        <input name="password_old" type="password" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="password_new1">Nueva contraseña</label>
                                <input name="password_new1" type="password" class="form-control"/>
                            </div>
                            <div class="col-md-6">
                                <label for="password_new2">Confirmar nueva contraseña</label>
                                <input name="password_new2" type="password" class="form-control"/>
                            </div>
                        </div>
                    </div>
                <input type="submit" value="Guardar" class="btn btn-primary btn-block"/>
            </form>
          </div>
        </div>
    </div>

{% endblock %}

{% block bodyss %}
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.j' %}s"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script src="{% static 'js/buttons.js' %}"></script>
{% endblock %}