apps/users/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import password_reset, password_reset_confirm

app_name = 'users'

urlpatterns = [
    path('new', views.create_new_emplooye, name='new'),
    path('login', views.LoginEmplooyeeView.as_view(), name='login'),
    path('logout', views.logout , name='logout'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),

    path('reset/password_reset', password_reset, {
        'template_name':'mails/reset_password/password_reset_form.html',
        'email_template_name': 'mails/reset_password/password_reset_email.html'
        }, name='password_reset'),

    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, { 
            'template_name':'mails/reset_password/password_reset_confirm.html'
            }, name='password_reset_confirm' ),    
]

votes/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.contrib.auth.views import password_reset_done, password_reset_complete
from .views import index, error_404

urlpatterns = [
    path('', index),
    path('superadmin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('votings/', include('apps.votings.urls')),
    path('management/', include('apps.management.urls')),
    path('password_reset/done', password_reset_done, {
        'template_name':'mails/reset_password/password_reset_done.html'
        }, name='password_reset_done' ),
    path('reset/password_reset_complete', password_reset_complete, {
        'template_name':'mails/reset_password/password_reset_complete.html'
        }, name='password_reset_complete'),
    re_path('[^ ]/', error_404),
]

apps/users/models.py
from django.db import models

class Delegacion(models.Model):
    nombre = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        return '{}'.format(self.nombre)

class Padron(models.Model):
    numero_de_empleado = models.PositiveIntegerField(default=0)
    nombre_completo = models.CharField(max_length=255, blank=False, null=False)
    delegacion = models.ForeignKey(Delegacion, on_delete=models.PROTECT)
    status = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.numero_de_empleado)

apps/users/forms.py
from django import forms
from django.db import models
from .models import Delegacion
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class DelegacionForm(forms.ModelForm):
    nombre = models.CharField(max_length=50, blank=False, null=False)

    def __init__(self, *args, **kwargs):
        super(DelegacionForm, self).__init__(*args, **kwargs)
        # no solo clases cualquier otro atributo se puede
        self.fields['nombre'].widget.attrs.update({'class':'form-control', 'placeholder':'Nombre'})

    class Meta:
        model = Delegacion
        fields = [
            'nombre',
        ]

class CreateEmplooyeeForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]
        labels = {
            'username': 'Numero de empleado',
            'first_name': 'Nombres',
            'last_name': 'Apellidos',
            'email': 'Correo Institucional',
            'password1': 'Contraseña',
            'password2': 'Confirmar contraseña',
        }   
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control','placeholder':'Por ejemplo: 12345','required':True}),
            'first_name': forms.TextInput(attrs={'class':'form-control','type':'text','placeholder':'Por ejemplo: Cesar Ernesto','required':True}),
            'last_name': forms.TextInput(attrs={'class':'form-control','type':'text','placeholder':'Por ejemplo: Salazar Buelna','required':True}),
            'email': forms.EmailInput(attrs={'pattern':'[a-z0-9._-]+@([a-z0-9_-]+\.)*(uson\.|unison\.|staus\.)([a-z0-9_-]+\.)*[a-z]{2,4}$','class':'form-control','placeholder':'Por ejemplo: abcdef@mat.uson.mx','required':True}),
            #'email': forms.EmailInput(attrs={'class':'form-control','placeholder':'Por ejemplo: abcdef@mat.uson.mx','required':True}),
            'password1': forms.PasswordInput(attrs={'class':'form-control','placeholder':''}),
            'password2': forms.PasswordInput(attrs={'class':'form-control','placeholder':''}),
        }
    
class LoginEmplooyeeForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginEmplooyeeForm, self).__init__(*args, **kwargs)
        # no solo clases cualquier otro atributo se puede
        self.fields['username'].widget.attrs.update({'class':'form-control','placeholder':'Número de empleado'})
        self.fields['password'].widget.attrs.update({'class':'form-control','placeholder':''})

    class Meta:
        model = User
        fields = [
            'username',
            'password',
        ]
        labels = {
            'username': 'Numero de empleado',
            'password': 'Contraseña',
        }

apps/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View, CreateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate, login as login_django, logout as logout_django
from django.contrib.auth.decorators import login_required
from .models import Delegacion, Padron
from django.contrib.auth.models import User
from .forms import DelegacionForm, CreateEmplooyeeForm, LoginEmplooyeeForm

from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string

def get_delegacion_names():
    delegaciones = list(Delegacion.objects.all().values())
    delegaciones_names = []
    
    for d in delegaciones:
        if d['nombre'] != "TODAS":
            delegaciones_names.append( d['nombre'] )

    delegaciones_names.sort()

    return delegaciones_names

def validate_user(user):
    try:
        if ('username' in user) and ('email' in user) and ('delegacion' in user): 
            padron = Padron.objects.get(numero_de_empleado=user['username']) 
            user = User.objects.get(email=user['email']) 
            user = User.objects.get(username=user['username'])
            return 1 # Usuario ya registrado
        else:
            return 2
    except Padron.DoesNotExist:
        return 2 # el padron
    except User.DoesNotExist:
        if padron.delegacion.nombre != user['delegacion']:
            return 3 # Delegación incorrecta
        elif padron.status == False:
            return 4 # el status es no activo
        else:
            return 5 # es valido
    except:
        return 2

def send_email(user, request):
    # get dominio
    current_site = get_current_site(request)
    # asunto y mensaje
    subject = 'Activa tu cuenta'
    message = render_to_string('mails/activar_cuenta.html', {
        'user': user,
        'domain': current_site.domain,
        'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
        'token':account_activation_token.make_token(user),
    })
    # crea y envia el mensaje
    email = EmailMessage(
        subject, message, to=[request.POST['email']]
    )
    email.send()

def create_new_emplooye(request):
    if request.user.is_authenticated:
        return redirect('votings:index')

    msg = None

    if request.method == 'POST':
        tipo_error = validate_user(request.POST)   
        if tipo_error == 1:
            msg = 'Usuario ya registrado'
        elif tipo_error == 2:
            msg = 'El número de empleado no se encuentra en el padrón'
        elif tipo_error == 3:
            msg = 'El número de empleado no coincide con la delegación'
        elif tipo_error == 4:
            msg = 'Su estado en el padrón es inactivo'
        else: 
            form = CreateEmplooyeeForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                send_email(user, request)
                # manda una aviso de que active su cuenta    
                return render(request, 'users/new.html', {
                    'form': form,
                    'msg': None,
                    'activate': True, 
                    'd_names': get_delegacion_names()
                })
            # envia los error al context y los renderiza
            return render(request, 'users/new.html', {
                'form': form,
                'msg': None,
                'activate': False, 
                'd_names': get_delegacion_names(),
                'user': {
                    'username': request.POST['username'],
                    'first_name': request.POST['first_name'],
                    'last_name': request.POST['last_name'],
                    'email': request.POST['email'],
                    'delegacion': request.POST['delegacion'] 
                }
            })
    
        # hubo un error
        return render(request, 'users/new.html', {
            'form': CreateEmplooyeeForm(),
            'msg': msg,
            'activate': False, 
            'd_names': get_delegacion_names(),
            'user': {
                'username': request.POST['username'],
                'first_name': request.POST['first_name'],
                'last_name': request.POST['last_name'],
                'email': request.POST['email'],
                'delegacion': request.POST['delegacion'] 
            }
        })

    else:
        # si es get o hubo un error
        return render(request, 'users/new.html', {
            'form': CreateEmplooyeeForm(),
            'msg': msg,
            'activate': False, 
            'd_names': get_delegacion_names()
        })

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    # if user is not None and account_activation_token.check_token(user, token):
    if user is not None:
        user.is_active = True
        user.save()
        return render(request, 'users/activate.html', {
            'message':'Gracias por la verificación de su correo electrónico. Ahora puede iniciar sesión con cuenta.'
        })
    else:
        return render(request, 'users/activate.html', {
            'message':'¡El enlace de activación no es válido!'
        })

class LoginEmplooyeeView(CreateView):
    form = LoginEmplooyeeForm()
    template = 'users/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('votings:index')
        
        if 'show' not in request.session:
            request.session['show'] = False
            return render(request, self.template, {'form': self.form, 'show':True})
        else:
            return render(request, self.template, {'form': self.form, 'show':False})

    def post(self, request, *args, **kwargs):
        username_post = request.POST['username'] if 'username' in request.POST else 'noexiste' 
        password_post = request.POST['password'] if 'password' in request.POST else 'noexiste'

        user = authenticate(username=username_post, password=password_post)

        if user is not None:
            login_django(request, user)
            if request.user.is_staff == False:
                return redirect('votings:index')
            else:
                return redirect('management:voting_list')
        else:
            messages.error(request, 'Numero de empleado o contraseña incorrecta')   
        return render(request, self.template, {
            'form': self.form,
            'user': {
                'username': request.POST['username'],
                'password': request.POST['password'],
            }
        })

@login_required(login_url='users:login')
def logout(request):
    logout_django(request)
    return redirect('users:login')

templates/users/activate.html
{% extends 'base/baseOut.html' %}
{% block title %}Verificación de correo{% endblock %}

{% block headss %} 
    {% load staticfiles %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template--> 
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Breadcrumbs-->
    <div class="card card-login mx-auto mt-5">
        <div class="card-header" align="center">
            <img src="{% static 'images/logoNombre.png' %}" width="247" height="91" alt="STAUS" alin>
        </div>
        <div class="card-header" align="center">
            Verificación de correo
        </div>
        <div class="card-body">
            <div align="center">
                <h4>{{message}}</h4>
            </div>
            <div class="text-center">
                <a class="d-block small" href="{% url 'users:login' %}">Iniciar Sesión</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block bodyss %}
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script src="{% static 'js/buttons.js' %}"></script>
{% endblock %}

templates/users/login.html
{% extends 'base/baseOut.html' %}
{% block title %}Inicio de Sesión{% endblock %}

{% block headss %} 
    {% load staticfiles %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template--> 
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Breadcrumbs-->
    <div class="card card-login mx-auto mt-5">
        <div class="card-header" align="center">
            <img src="{% static 'images/logoNombre.png' %}" width="247" height="91" alt="STAUS" alin>
        </div>
        <div class="card-header" align="center">
            Iniciar Sesión
        </div>
        <div class="card-body">
            <form method="post">{% csrf_token %}
                
                {% if messages %}
                    {% for message in messages  %}
                    {% if message.tags == 'error' %} 
                    <div class="alert alert-danger" role="alert">
                        Usuario o contraseña incorrectos.
                    </div>
                    {% endif %}
                    {% endfor %}
                {% endif %}

                {% if user %}
                    <div class="form-group">
                        <label for="{{form.username.name}}">Número de empleado</label>
                        <input name="username" value="{{ user.username }}" class="form-control" placeholder="Por ejemplo: 12345" required="" id="id_username">
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{form.username.name}}">Número de empleado</label>
                        <input name="username" class="form-control" placeholder="Por ejemplo: 12345" required="" id="id_username">
                    </div>
                {% endif %}

                    <div class="form-group">
                        <label for="{{form.password.name}}">Contraseña</label>
                        {{form.password}}
                    </div>
                <input type="submit" class="btn button-caution btn-block" value="Ingresar">
            </form>
            <div class="text-center">
                <a class="d-block small mt-3" href="{% url 'users:new' %}">Registrarse</a>
                <a class="d-block small" href="{% url 'users:password_reset' %}">¿Olvidaste tu contraseña?</a>
            </div>
        </div>
        {% if show == True %}
            <div id="loginModal" tabindex="-1" role="dialog" class="modal">
                <div role="document" class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title">Aviso</h5>
                    <button type="button" data-dismiss="modal" aria-label="Close" class="close"></button><span aria-hidden="true">×</span>
                    </div>
                    <div class="modal-body">
                    <p>Bienvenidos al sistema electrónico de consulta del STAUS.
                        Para poder participar debe de estar registrado en el sistema. Puede registrarse en el siguiente enlace: <a href="{% url 'users:new' %}">Registrarse</a> </p>
                    </div>
                    <div class="modal-footer">
                        <button data-dismiss='modal' class="btn btn-primary">Aceptar</button>
                    </div>
                </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block bodyss %}
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script src="{% static 'js/buttons.js' %}"></script>
    <script language="javascript" type="text/javascript">
        $(document).ready(function(){
            $('#loginModal').modal('show')
        });
    </script>
{% endblock %}

templates/users/new.html
{% extends 'base/baseOut.html' %}
{% block title %}Registro{% endblock %}

{% block headss %} 
    {% load staticfiles %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template--> 
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Breadcrumbs-->
    <div class="card card-register mx-auto mt-5">
        <div class="card-header" align="center">
            <img src="{% static 'images/logoNombre.png' %}" width="247" height="91" alt="STAUS" alin>
        </div>
        <div class="card-header" align="center">
            Registrarse
        </div>
        <div class="card-body">
            <form method="post">{% csrf_token %}

                {% if msg %}
                    <div class="alert alert-danger" role="alert">
                        {{ msg }}
                    </div>
                {% endif %}
                {% if form.errors %}
                {% for key, value in form.errors.items %}
                        <div class="alert alert-danger" role="alert">
                            {{value}}
                        </div>
                    {% endfor %}
                {% endif %}

                {% if user%}
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="first_name">Nombres</label>
                                <input type="text" value="{{ user.first_name }}" name="first_name" class="form-control" placeholder="Por ejemplo: Cesar Ernesto" required="" maxlength="30" id="id_first_name">
                            </div>
                            <div class="col-md-6">
                                <label for="last_name">Apellidos</label>
                                <input type="text" value="{{ user.last_name }}" name="last_name" class="form-control" placeholder="Por ejemplo: Salazar Buelna" required="" maxlength="150" id="id_last_name">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-12">
                                <label for="delegacion">Delegación</label>
                                <select class="form-control" name="delegacion" id="station">
                                    {% for d in d_names %}
                                        {% if d == user.delegacion %}
                                            <option selected>{{ d }}</option>
                                        {% else %}
                                            <option>{{ d }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="username">Número de empleado</label>
                                <input type="text" value="{{ user.username }}" name="username" class="form-control" placeholder="Por ejemplo: 12345" required="" maxlength="150" autofocus="" id="id_username">
                            </div>
                            <div class="col-md-6">
                                <label for="email">Correo Institucional</label>
                                <input type="email" value="{{ user.email }}" name="email" pattern="[a-z0-9._-]+@([a-z0-9_-]+\.)*(uson\.|unison\.|staus\.)([a-z0-9_-]+\.)*[a-z]{2,4}$" class="form-control" placeholder="Por ejemplo: abcdef@mat.uson.mx" required="" maxlength="254" id="id_email">
                            </div>
                        </div>
                    </div>
                {% else %}
                <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="{{form.first_name.name}}">Nombres</label>
                                {{form.first_name}}
                            </div>
                            <div class="col-md-6">
                                <label for="{{form.last_name.name}}">Apellidos</label>
                                {{form.last_name}}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-12">
                                <label for="delegacion">Delegación</label>
                                <select class="form-control" name="delegacion" id="station">
                                    {% for d in d_names %}
                                        <option>{{ d }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="{{form.username.name}}">Número de empleado</label>
                                {{form.username}}
                            </div>
                            <div class="col-md-6">
                                <label for="{{form.email.name}}">Correo Institucional</label>
                                {{form.email}}
                            </div>
                        </div>
                    </div>
                {% endif %}
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="{{form.password1.name}}">Contraseña</label>
                                <input class="form-control" placeholder="" name="password1" type="password" required>
                            </div>
                            <div class="col-md-6">
                                <label for="{{form.password2.name}}">Confirmar contraseña</label>
                                <input class="form-control" placeholder="" name="password2" type="password" required>
                            </div>
                        </div>
                    </div>
                    
                <input type="submit" class="btn button-caution btn-block" value="Registrar">
            </form>
            <div class="text-center">
                    <a class="d-block small mt-3" href="{% url 'users:login' %}">¿Ya tienes cuenta?</a>
                </div>
        </div>
    </div>
    {% if activate == True %}
        <div id="registroModal" tabindex="-1" role="dialog" class="modal">
            <div role="document" class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title">Registro</h5>
                <button type="button" data-dismiss="modal" aria-label="Close" class="close"></button><span aria-hidden="true">×</span>
                </div>
                <div class="modal-body">
                <p>Para completar el registro, se enviara un enlace de verificación a su correo.</p>
                </div>
                <div class="modal-footer"><a href="{% url 'users:login' %}" class="btn btn-primary">Aceptar</a></div>
            </div>
            </div>
        </div>
    {% endif %}
    
{% endblock %}

{% block bodyss %}
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script language="javascript" type="text/javascript">
        $(document).ready(function(){
            $('#registroModal').modal('show')
        });
    </script>
{% endblock %}